@startuml
!theme cerulean-outline
box "Accept Friend Request"
actor "User" as user
participant "disp:Display Manager" as disp
participant "msg:Message Manager" as msg
participant "sess:Session Manager" as sess
participant "frie:Friend Manager" as frie
participant "notif:Notification Manager" as notif
actor "Friend User" as friend
end box
activate user
user -> disp ++ : ACCEPT_REQUEST
disp -> msg ++ : accept(friend_request)
msg -> sess ++ : getSessionID()
sess --> msg : session_ID
msg -> sess : getSessionID(friend_model)
sess --> msg -- : friend_session_ID
msg -> frie ++ : addFriend(session_ID,friend_session_ID)
frie -> frie : connect(session_ID,friend_session_ID)
frie --> msg -- : SUCCESS
msg -> notif ++ : friendAdded(session_ID,friend_session_ID)
notif --> msg : addMsg(FRIEND_ADDED,session_ID,friend_session_ID)
notif -> friend --: notify(FRIEND_ADDED,session_ID)
msg --> disp -- : SUCCESS
disp --> user -- : "[Name] added"
deactivate user
@enduml
