@startuml
!theme cerulean-outline
box "Decline Friend Request"
actor "User" as user
participant "disp:UI View" as disp
participant "msg:Message Controller" as msg
participant "sess:Session Database" as sess
participant "notif:Notification Hub" as notif
actor "Friend User" as friend
end box
activate user
user -> disp ++ : DECLINE_REQUEST
disp -> msg ++ : decline(friend_request)
msg -> sess ++ : getSessionID()
sess --> msg : session_ID
msg -> sess : getSessionID(friend_model)
sess --> msg -- : friend_session_ID
msg -> notif ++ : friendDecline(session_ID,friend_session_ID)
notif --> msg : addMsg(FRIEND_DECLINE,session_ID,friend_session_ID)
notif -> friend --: notify(FRIEND_DECLINE,session_ID)
msg --> disp -- : SUCCESS
disp --> user -- : "[Name] declined"
deactivate user
@enduml
