@startuml
!theme cerulean-outline
box "Search Friend"
actor "User" as user
participant "disp:UI View" as disp
participant "sess:Session Database" as sess
participant "prof:Profile Database" as prof
participant "frie:Friend Controller" as frie
end box
|||
activate user
ref over user, disp, sess, prof: View All Friend
user -> disp ++ : SEARCH_FRIEND
disp --> user : "Enter friend name"
user -> disp : friend_name
disp -> disp : filter(friend_profile_list, friend_name)
disp --> user --: display(filtered_friend_profile_list)
deactivate user
@enduml