@startuml
!theme cerulean-outline
box "Cancel Split Creation"
actor "User" as user
participant "disp:UI View" as disp
participant "splt:Split Controller" as splt
participant "sess:Session Database" as sess
end box
activate user
user -> disp ++ : CANCEL_SPLIT_REQUEST
user -> disp : split_model
disp -> splt ++ : cancel(split_model)
splt -> sess ++ : getSessionID()
sess --> splt -- : sessionID
splt -> splt : remove(sessionID, split_model)
splt --> disp -- : SUCCESS
disp --> user -- : "Canceled split creation"
deactivate user
@enduml