@startuml
!theme cerulean-outline
box "Create Split Request"
actor "User" as user
participant "disp:Display Manager" as disp
participant "splt:Split Manager" as splt
participant "gro:Group Manager" as gro
participant "sess:Session Manager" as sess
participant "msg:Message Manager" as msg
participant "notif:Notification Manager" as notif
participant "prof:Profile Manager" as prof
participant "frie:Friend Manager" as frie
actor "Split Members" as splitMembers
actor "New Split Member" as newSpMem
end box
activate user
user -> disp ++ : SPLIT_REQUEST
disp -> splt ++ : createSplit()
splt --> disp -- : split_model
disp --> user -- : "Choose member"
user -> disp ++ : split_model
ref over user, newSpMem : Add People to Split Request via Friend
ref over user, newSpMem : Add People to Split Request via Group
deactivate disp
user -> disp ++ : split_model
user -> disp : split_info
note right of user
  total amount, 
  payment categories, 
  split amounts,
end note
disp -> splt ++ : update(split_model, split_info)
splt --> disp -- : split_model
disp --> user -- : "Choose Split Type"
ref over user, sess : Change Split Type
opt CANCEL_SPLIT
  ref over user, sess : Cancel Split Request
end
splt -> splt ++: getSplitMember(split_model)
splt -> msg ++ : split_member_ID
splt -> msg : SPLIT_ACCEPT
ref over notif, msg, splitMembers : Notify Split Member
msg --> splt -- : SUCCESS
splt --> disp -- : SUCCESS
disp --> user -- : "Split created"
deactivate user
@enduml