@startuml
!theme cerulean-outline
box "Direct Friend Payment"
actor "User" as user
participant "disp:UI View" as disp
participant "sess:Session Database" as sess
participant "prof:Profile Database" as prof
participant "frie:Friend Controller" as frie
participant "pay:Payment Controller" as pay
participant "msg:Message Controller" as msg
participant "notif:Notification Hub" as notif
actor "Friend" as friend
actor "Payment System" as paySys
end box
activate user
user -> disp ++ : DIRECT_PAYMENT
disp --> user : "Choose Friend"
ref over user, frie : Search Friend
user -> disp : friend_model
user -> disp : monetary_amount
disp -> frie ++: pay(friend_model, monetary_amount)
frie -> pay ++ : monetary_amount 
ref over pay, paySys : Verify Balance
pay --> frie -- : verification_status
opt verification_status == SUFFICIENT
  frie -> pay ++: reduce(sessionID, monetary_amount)
  pay -> paySys ++ : process(monetary_amount)
  paySys --> pay -- : process_status
  pay --> frie -- : process_status
  opt process_status == SUCCESS
    frie -> sess ++ : getSessionID(friend_model)
    sess --> frie --: friend_session_ID
    frie --> notif ++ : directPay(session_ID,friend_session_ID, monetary_amount)
    notif --> msg : addMsg(DIRECT_PAY,session_ID,friend_session_ID, monetary_amount)
    notif -> friend --: notify(DIRECT_PAY,session_ID, monetary_amount)
    frie --> disp -- : SUCCESS
    disp --> user -- : "Pay [Name] $[Amount]"
  end
end
deactivate user
@enduml