@startuml
!theme cerulean-outline
box "View Split Request"
actor "User" as user
participant "disp:UI View" as disp
participant "msg:Message Controller" as msg
participant "sess:Session Database" as sess
end box
activate user
|||
ref over user, sess : View Inbox 
user -> disp ++ : VIEW_SPLIT_REQUEST
disp -> disp : filter(inbox_msg_list, SPLIT_REQUEST)
disp --> user : display(split_requests)
@enduml