@startuml
!theme cerulean-outline
box "View Split Request"
actor "User" as user
participant "disp:Display Manager" as disp
participant "msg:Message Manager" as msg
participant "sess:Session Manager" as sess
end box
activate user
|||
ref over user, sess : View Inbox 
user -> disp ++ : VIEW_SPLIT_REQUEST
disp -> disp : filter(inbox_msg_list, SPLIT_REQUEST)
disp --> user : display(split_requests)
@enduml