@startuml logout
!theme cerulean-outline
box "Log Out"
actor "User" as user
participant "disp:UI View" as disp
participant "sess:Session Database" as sess
end box
activate user
user -> disp ++ : LOGOUT
disp -> sess ++ : request(LOGOUT)
sess -> sess : remove session ID
sess --> disp : ACCEPTED
disp --> user -- : redirect(LOGIN_SCREEN)
deactivate user
@enduml