@startuml view_profile
!theme cerulean-outline
box "View Personal Profile"
actor "User" as user
participant "disp:UI View" as disp
participant "prof:Profile Database" as prof
participant "sess:Session Database" as sess
end box
activate user
user -> disp ++ : ENTER_PROFILE
disp -> prof ++ : retrive_profile()
prof -> sess ++ : retrieve_ID()
sess --> prof -- : session_ID
prof -> prof : getProfile(session_ID)
prof --> disp -- : profile_info
disp --> user -- : display(profile_info)
deactivate user
@enduml